/**
 * Local, clearly-separated mock legal corpus used only when
 * LEGAL_PROVIDER=mock (development / demo without external API credentials).
 *
 * This data is illustrative of real Indian statutes and reported judgments
 * but MUST NOT be presented as a complete or currently-authoritative legal
 * corpus, and must never be blended with data returned by a real provider.
 * Every record is tagged provider: "mock" downstream so the UI can make
 * this explicit to the user.
 */

export const MOCK_SOURCES = [
  {
    providerSourceId: 'bns-318',
    title: 'Bharatiya Nyaya Sanhita, 2023 — Section 318: Cheating',
    sourceType: 'section',
    url: 'https://www.indiacode.nic.in/handle/123456789/20062',
    act: 'Bharatiya Nyaya Sanhita, 2023',
    section: '318',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '2023-12-25',
    effectiveDate: '2024-07-01',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'Whoever, by deceiving any person, fraudulently or dishonestly induces the person so deceived to deliver any property to any person, or to consent that any person shall retain any property, or intentionally induces the person so deceived to do or omit to do anything which he would not do or omit if he were not so deceived, and which act or omission causes or is likely to cause damage or harm to that person in body, mind, reputation or property, is said to "cheat". ' +
      'Explanation.—A dishonest concealment of facts is a deception within the meaning of this section. ' +
      'Whoever cheats shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both; and if the person cheated is induced to deliver any property, the term may extend to seven years, and shall also be liable to fine. ' +
      'This section corresponds to Section 415/420 of the repealed Indian Penal Code, 1860.',
    concepts: ['deception', 'fraudulent inducement', 'dishonest inducement', 'cheating', 'delivery of property', 'money transfer fraud'],
  },
  {
    providerSourceId: 'bns-319',
    title: 'Bharatiya Nyaya Sanhita, 2023 — Section 319: Cheating by personation',
    sourceType: 'section',
    url: 'https://www.indiacode.nic.in/handle/123456789/20062',
    act: 'Bharatiya Nyaya Sanhita, 2023',
    section: '319',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '2023-12-25',
    effectiveDate: '2024-07-01',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'A person is said to "cheat by personation" if he cheats by pretending to be some other person, or by knowingly substituting one person for another, or representing that he or any other person is a person other than he or such other person really is. ' +
      'Explanation.—The offence is committed whether the individual personated is a real or imaginary person. ' +
      'Whoever cheats by personation shall be punished with imprisonment of either description for a term which may extend to five years, or with fine, or with both.',
    concepts: ['impersonation', 'identity fraud', 'online fraud', 'cheating'],
  },
  {
    providerSourceId: 'it-act-66d',
    title: 'Information Technology Act, 2000 — Section 66D: Cheating by personation using computer resource',
    sourceType: 'section',
    url: 'https://www.indiacode.nic.in/handle/123456789/1999',
    act: 'Information Technology Act, 2000',
    section: '66D',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '2000-06-09',
    effectiveDate: '2009-10-27',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'Whoever, by means of any communication device or computer resource, cheats by personation, shall be punished with imprisonment of either description for a term which may extend to three years and shall also be liable to fine which may extend to one lakh rupees.',
    concepts: ['online fraud', 'phishing', 'impersonation', 'digital payment fraud', 'UPI fraud'],
  },
  {
    providerSourceId: 'pow-act-1936-s3',
    title: 'Payment of Wages Act, 1936 — Section 3: Responsibility for payment of wages',
    sourceType: 'section',
    url: 'https://labour.gov.in/sites/default/files/payment_of_wages_act1936.pdf',
    act: 'Payment of Wages Act, 1936',
    section: '3',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '1936-04-23',
    effectiveDate: '1937-03-28',
    repealDate: null,
    currentStatus: 'amended',
    fullText:
      'Every employer shall be responsible for the payment to persons employed by him of all wages required to be paid under this Act. ' +
      'Provided that, in the case of persons employed (otherwise than by a contractor) in factories, if a person has been named as the manager of the factory, and in the case of persons employed by a contractor, if the contractor has named a person to be responsible for such payments, such persons shall also be responsible.',
    concepts: ['unpaid wages', 'wage obligation', 'employer liability', 'employment'],
  },
  {
    providerSourceId: 'pow-act-1936-s5',
    title: 'Payment of Wages Act, 1936 — Section 5: Time of payment of wages',
    sourceType: 'section',
    url: 'https://labour.gov.in/sites/default/files/payment_of_wages_act1936.pdf',
    act: 'Payment of Wages Act, 1936',
    section: '5',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '1936-04-23',
    effectiveDate: '1937-03-28',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'The wages of every person employed shall be paid before the expiry of the seventh day (or tenth day, where more than 1000 persons are employed) after the last day of the wage period in respect of which the wages are payable. ' +
      'Where the employment of any person is terminated by or on behalf of the employer, the wages earned by him shall be paid before the expiry of the second working day from the day on which his employment is terminated.',
    concepts: ['unpaid wages', 'wage payment deadline', 'termination', 'final settlement'],
  },
  {
    providerSourceId: 'id-act-1947-s25f',
    title: 'Industrial Disputes Act, 1947 — Section 25F: Conditions precedent to retrenchment',
    sourceType: 'section',
    url: 'https://labour.gov.in/sites/default/files/THE INDUSTRIAL DISPUTES ACT1947.pdf',
    act: 'Industrial Disputes Act, 1947',
    section: '25F',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '1947-03-11',
    effectiveDate: '1947-04-01',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'No workman employed in any industry who has been in continuous service for not less than one year under an employer shall be retrenched by that employer until— (a) the workman has been given one month\'s notice in writing indicating the reasons for retrenchment, or wages in lieu of such notice; (b) the workman has been paid, at the time of retrenchment, compensation equivalent to fifteen days\' average pay for every completed year of continuous service; and (c) notice has been served on the appropriate Government.',
    concepts: ['termination', 'retrenchment', 'wrongful dismissal', 'employment', 'notice pay'],
  },
  {
    providerSourceId: 'tp-act-1882-s108',
    title: 'Transfer of Property Act, 1882 — Section 108: Rights and liabilities of lessor and lessee',
    sourceType: 'section',
    url: 'https://www.indiacode.nic.in/handle/123456789/2337',
    act: 'Transfer of Property Act, 1882',
    section: '108',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '1882-02-17',
    effectiveDate: '1882-07-01',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'In the absence of a contract or local usage to the contrary, the lessor and the lessee of immovable property, as against one another, respectively, possess the rights and are subject to the liabilities mentioned in the rules next following, or such of them as are applicable to the property leased. ' +
      '(l) the lessee may... on the determination of the lease, remove... all things which he has attached to the earth... the lessee is bound to put the lessor into possession of the property.',
    concepts: ['tenancy', 'lease', 'landlord obligation', 'possession on termination'],
  },
  {
    providerSourceId: 'model-tenancy-2021-s10',
    title: 'Model Tenancy Act, 2021 — Section 10: Security deposit',
    sourceType: 'act',
    url: 'https://mohua.gov.in/upload/uploadfiles/files/Model%20Tenancy%20Act.pdf',
    act: 'Model Tenancy Act, 2021',
    section: '10',
    court: null,
    jurisdiction: 'India (State — as adopted)',
    jurisdictionLevel: 'state',
    state: null,
    date: '2021-06-02',
    effectiveDate: null,
    repealDate: null,
    currentStatus: 'unknown',
    fullText:
      'The security deposit payable by the tenant shall not exceed two months\' rent in case of residential premises. ' +
      'The landlord shall return the security deposit to the tenant, after making due deductions, on the date of taking over vacant possession of the premises. ' +
      'Note: The Model Tenancy Act is a template statute circulated by the Union Government for States/UTs to adopt or adapt through their own legislation; it does not by itself have the force of law unless enacted by a State legislature. Verify whether it, or a corresponding State Rent Act, has been adopted in the relevant state before relying on it.',
    concepts: ['security deposit', 'tenancy', 'landlord obligation', 'deposit refund', 'property damage deduction'],
  },
  {
    providerSourceId: 'cp-act-2019-s2-9',
    title: 'Consumer Protection Act, 2019 — Section 2(9): Definition of "deficiency"',
    sourceType: 'section',
    url: 'https://consumeraffairs.nic.in/acts-and-rules/consumer-protection-act-2019',
    act: 'Consumer Protection Act, 2019',
    section: '2(9)',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '2019-08-09',
    effectiveDate: '2020-07-20',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      '"deficiency" means any fault, imperfection, shortcoming or inadequacy in the quality, nature and manner of performance which is required to be maintained by or under any law for the time being in force or has been undertaken to be performed by a person in pursuance of a contract or otherwise in relation to any service and includes— (i) any act of negligence or omission or commission by such person which causes loss or injury to the consumer; and (ii) deliberate withholding of relevant information by such person to the consumer.',
    concepts: ['service deficiency', 'consumer complaint', 'contractual obligation', 'withheld information'],
  },
  {
    providerSourceId: 'bns-351',
    title: 'Bharatiya Nyaya Sanhita, 2023 — Section 351: Criminal intimidation',
    sourceType: 'section',
    url: 'https://www.indiacode.nic.in/handle/123456789/20062',
    act: 'Bharatiya Nyaya Sanhita, 2023',
    section: '351',
    court: null,
    jurisdiction: 'India (Central)',
    jurisdictionLevel: 'central',
    state: null,
    date: '2023-12-25',
    effectiveDate: '2024-07-01',
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'Whoever threatens another with any injury to his person, reputation or property, or to the person or reputation of any one in whom that person is interested, with intent to cause alarm to that person, or to cause that person to do any act which he is not legally bound to do, or to omit to do any act which that person is legally entitled to do, as the means of avoiding the execution of such threat, commits criminal intimidation.',
    concepts: ['threat', 'intimidation', 'coercion', 'harassment'],
  },
];

export const MOCK_JUDGMENTS = [
  {
    providerSourceId: 'sc-1994-hira-lal',
    title: 'Hira Lal Hari Lal Bhagwati v. C.B.I. — on cheating and dishonest inducement',
    sourceType: 'judgment',
    url: 'https://main.sci.gov.in/judgments',
    act: 'Indian Penal Code, 1860 (Section 420) / Bharatiya Nyaya Sanhita, 2023 (Section 318)',
    section: null,
    court: 'Supreme Court of India',
    jurisdiction: 'India',
    jurisdictionLevel: 'central',
    state: null,
    date: '2003-08-14',
    effectiveDate: null,
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'The Court held that to constitute the offence of cheating, the intention to deceive should be in existence at the time when the inducement was offered and the property or advantage was parted with; a mere breach of contract, absent dishonest inducement at inception, does not by itself amount to cheating.',
    concepts: ['cheating', 'dishonest inducement', 'intention at inception', 'breach of contract distinction'],
  },
  {
    providerSourceId: 'del-hc-2016-wage-recovery',
    title: 'Illustrative Delhi High Court order on recovery of unpaid wages under the Payment of Wages Act',
    sourceType: 'order',
    url: 'https://delhihighcourt.nic.in/',
    act: 'Payment of Wages Act, 1936',
    section: '15',
    court: 'Delhi High Court',
    jurisdiction: 'Delhi',
    jurisdictionLevel: 'state',
    state: 'Delhi',
    date: '2016-11-02',
    effectiveDate: null,
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'The Authority under the Payment of Wages Act has summary jurisdiction to direct payment of wages wrongly withheld, together with compensation, on an application made by the employee within the limitation period prescribed under Section 15 of the Act.',
    concepts: ['unpaid wages', 'wage recovery', 'authority jurisdiction', 'employment'],
  },
  {
    providerSourceId: 'bom-hc-2018-deposit-deduction',
    title: 'Illustrative Bombay High Court order on unreasonable deduction from a tenant\'s security deposit',
    sourceType: 'order',
    url: 'https://bombayhighcourt.nic.in/',
    act: 'Maharashtra Rent Control Act, 1999',
    section: null,
    court: 'Bombay High Court',
    jurisdiction: 'Maharashtra',
    jurisdictionLevel: 'state',
    state: 'Maharashtra',
    date: '2018-03-22',
    effectiveDate: null,
    repealDate: null,
    currentStatus: 'current',
    fullText:
      'A landlord seeking to withhold a security deposit on the ground of damage must produce contemporaneous evidence of the condition of the premises and the cost of repair; a bare assertion of damage, without more, is insufficient to justify withholding the deposit in full.',
    concepts: ['security deposit', 'property damage', 'burden of proof', 'tenancy dispute'],
  },
];
